In [2]:
# Supress Warnings

import warnings
warnings.filterwarnings('ignore')

In [3]:
import numpy as np
import pandas as pd

In [5]:
Base_Poll_MOM = pd.read_csv("D:\personal\MS\EDA\MOM_Diff.csv")

In [6]:
Grp_Base_Poll_10=pd.read_csv('D:\personal\MS\EDA\Grp_Base_Poll_10.csv')
Grp_Base_Poll_90=pd.read_csv('D:\personal\MS\EDA\Grp_Base_Poll_90.csv')

In [7]:
Grp_Base_Poll_10['TS']=Grp_Base_Poll_10.year_number*10000+Grp_Base_Poll_10.month_number*10
Grp_Base_Poll_90['TS']=Grp_Base_Poll_90.year_number*10000+Grp_Base_Poll_90.month_number*10

In [8]:
Grp_Base_Poll_10.sort_values(by=['City_Town_Village_Area', 'Type_of_Location','TS'],inplace=True)
Grp_Base_Poll_10.set_index(['City_Town_Village_Area', 'Type_of_Location','TS',],inplace=True)

In [9]:
Grp_Base_Poll_10.head()

                                                  Unnamed: 0  month_number  \
City_Town_Village_Area Type_of_Location TS
Akola                  Industrial       20110010           0             1
                                        20110020           4             2
                                        20110030           8             3
                                        20110040          11             4
                                        20110050          14             5

                                                  year_number   NO2  \
City_Town_Village_Area Type_of_Location TS
Akola                  Industrial       20110010         2011  10.4
                                        20110020         2011  10.2
                                        20110030         2011  10.0
                                        20110040         2011  12.6
                                        20110050         2011  11.0

                                                  RSPM_PM10   SO2  SPM
City_Town_Village_Area Type_of_Location TS
Akola                  Industrial       20110010      129.0   7.8  NaN
                                        20110020      138.2   8.2  NaN
                                        20110030      139.0   9.0  NaN
                                        20110040      164.2  11.6  NaN
                                        20110050      136.4   9.6  NaN

In [10]:
Grp_Base_Poll_90.sort_values(by=['City_Town_Village_Area', 'Type_of_Location','TS'],inplace=True)
Grp_Base_Poll_90.set_index(['City_Town_Village_Area', 'Type_of_Location','TS',],inplace=True)

In [11]:
##time
Grp_Base_Poll_90['month_number_diff']=Grp_Base_Poll_90.month_number-Grp_Base_Poll_90.groupby(level=['City_Town_Village_Area', 'Type_of_Location'])['month_number'].shift(1)
##NO2
Grp_Base_Poll_90['NO2_MOM_diff']=Grp_Base_Poll_90['NO2']-Grp_Base_Poll_90.groupby(level=['City_Town_Village_Area', 'Type_of_Location'])['NO2'].shift(1)
Grp_Base_Poll_90.loc[~((Grp_Base_Poll_90.month_number_diff==1) | (Grp_Base_Poll_90.month_number_diff==-11)),'NO2_MOM_diff']=None
##SO2
Grp_Base_Poll_90['SO2_MOM_diff']=Grp_Base_Poll_90['SO2']-Grp_Base_Poll_90.groupby(level=['City_Town_Village_Area', 'Type_of_Location'])['SO2'].shift(1)
Grp_Base_Poll_90.loc[~((Grp_Base_Poll_90.month_number_diff==1) | (Grp_Base_Poll_90.month_number_diff==-11)),'SO2_MOM_diff']=None
##RSPM_PM10
Grp_Base_Poll_90['RSPM_PM10_MOM_diff']=Grp_Base_Poll_90['RSPM_PM10']-Grp_Base_Poll_90.groupby(level=['City_Town_Village_Area', 'Type_of_Location'])['RSPM_PM10'].shift(1)
Grp_Base_Poll_90.loc[~((Grp_Base_Poll_90.month_number_diff==1) | (Grp_Base_Poll_90.month_number_diff==-11)),'RSPM_PM10_MOM_diff']=None

##SPM
Grp_Base_Poll_90['SPM_MOM_diff']=Grp_Base_Poll_90['SPM']-Grp_Base_Poll_90.groupby(level=['City_Town_Village_Area', 'Type_of_Location'])['SPM'].shift(1)
Grp_Base_Poll_90.loc[~((Grp_Base_Poll_90.month_number_diff==1) | (Grp_Base_Poll_90.month_number_diff==-11)),'SPM_MOM_diff']=None

In [12]:
##time
Grp_Base_Poll_10['month_number_diff']=Grp_Base_Poll_10.month_number-Grp_Base_Poll_10.groupby(level=['City_Town_Village_Area', 'Type_of_Location'])['month_number'].shift(1)
##NO2
Grp_Base_Poll_10['NO2_MOM_diff']=Grp_Base_Poll_10['NO2']-Grp_Base_Poll_10.groupby(level=['City_Town_Village_Area', 'Type_of_Location'])['NO2'].shift(1)
Grp_Base_Poll_10.loc[~((Grp_Base_Poll_10.month_number_diff==1) | (Grp_Base_Poll_10.month_number_diff==-11)),'NO2_MOM_diff']=None
##SO2
Grp_Base_Poll_10['SO2_MOM_diff']=Grp_Base_Poll_10['SO2']-Grp_Base_Poll_10.groupby(level=['City_Town_Village_Area', 'Type_of_Location'])['SO2'].shift(1)
Grp_Base_Poll_10.loc[~((Grp_Base_Poll_10.month_number_diff==1) | (Grp_Base_Poll_10.month_number_diff==-11)),'SO2_MOM_diff']=None
##RSPM_PM10
Grp_Base_Poll_10['RSPM_PM10_MOM_diff']=Grp_Base_Poll_10['RSPM_PM10']-Grp_Base_Poll_10.groupby(level=['City_Town_Village_Area', 'Type_of_Location'])['RSPM_PM10'].shift(1)
Grp_Base_Poll_10.loc[~((Grp_Base_Poll_10.month_number_diff==1) | (Grp_Base_Poll_10.month_number_diff==-11)),'RSPM_PM10_MOM_diff']=None

##SPM
Grp_Base_Poll_10['SPM_MOM_diff']=Grp_Base_Poll_10['SPM']-Grp_Base_Poll_10.groupby(level=['City_Town_Village_Area', 'Type_of_Location'])['SPM'].shift(1)
Grp_Base_Poll_10.loc[~((Grp_Base_Poll_10.month_number_diff==1) | (Grp_Base_Poll_10.month_number_diff==-11)),'SPM_MOM_diff']=None

In [ ]:
Base_Poll_MOM,Grp_Base_Poll_10,Grp_Base_Poll_10

In [21]:
print(Base_Poll_MOM.columns)
print(Grp_Base_Poll_10.columns)
print(Grp_Base_Poll_90.columns)

Index(['index', 'ID', 'City_Town_Village_Area', 'Type_of_Location', 'TS',
       'year_number', 'month_number', 'NO2', 'RSPM_PM10', 'SO2', 'SPM',
       'Median_SO2_MOM_diff', 'month_number_diff', 'Median_NO2_MOM_diff',
       'Median_RSPM_PM10_MOM_diff', 'Median_SPM_MOM_diff'],
      dtype='object')
Index(['City_Town_Village_Area', 'Type_of_Location', 'TS', 'ID',
       'month_number', 'year_number', 'NO2', 'RSPM_PM10', 'SO2', 'SPM',
       'month_number_diff', 'P10_NO2_MOM_diff', 'P10_SO2_MOM_diff',
       'P10_RSPM_PM10_MOM_diff', 'P10_SPM_MOM_diff'],
      dtype='object')
Index(['City_Town_Village_Area', 'Type_of_Location', 'TS', 'ID',
       'month_number', 'year_number', 'NO2', 'RSPM_PM10', 'SO2', 'SPM',
       'month_number_diff', 'P90_NO2_MOM_diff', 'P90_SO2_MOM_diff',
       'P90_RSPM_PM10_MOM_diff', 'P90_SPM_MOM_diff'],
      dtype='object')

In [16]:
Base_Poll_MOM.columns=['ID', 'City_Town_Village_Area', 'Type_of_Location', 'TS',
       'year_number', 'month_number', 'NO2', 'RSPM_PM10', 'SO2', 'SPM',
       'Median_SO2_MOM_diff', 'month_number_diff', 'Median_NO2_MOM_diff',
       'Median_RSPM_PM10_MOM_diff', 'Median_SPM_MOM_diff']

In [17]:
Grp_Base_Poll_10.columns=['ID', 'month_number', 'year_number', 'NO2', 'RSPM_PM10', 'SO2',
       'SPM', 'month_number_diff', 'P10_NO2_MOM_diff', 'P10_SO2_MOM_diff',
       'P10_RSPM_PM10_MOM_diff', 'P10_SPM_MOM_diff']

In [18]:
Grp_Base_Poll_90.columns=['ID', 'month_number', 'year_number', 'NO2', 'RSPM_PM10', 'SO2',
       'SPM', 'month_number_diff', 'P90_NO2_MOM_diff', 'P90_SO2_MOM_diff',
       'P90_RSPM_PM10_MOM_diff', 'P90_SPM_MOM_diff']

In [19]:
Base_Poll_MOM.reset_index(inplace=True)
Grp_Base_Poll_10.reset_index(inplace=True)
Grp_Base_Poll_90.reset_index(inplace=True)

In [22]:
dfs = [Base_Poll_MOM, Grp_Base_Poll_10, Grp_Base_Poll_90]

In [24]:
from functools import reduce
df_final = reduce(lambda left,right: pd.merge(left,right,on=['City_Town_Village_Area', 'Type_of_Location', 'TS']), dfs)

In [25]:
df_final.columns

Index(['index', 'ID_x', 'City_Town_Village_Area', 'Type_of_Location', 'TS',
       'year_number_x', 'month_number_x', 'NO2_x', 'RSPM_PM10_x', 'SO2_x',
       'SPM_x', 'Median_SO2_MOM_diff', 'month_number_diff_x',
       'Median_NO2_MOM_diff', 'Median_RSPM_PM10_MOM_diff',
       'Median_SPM_MOM_diff', 'ID_y', 'month_number_y', 'year_number_y',
       'NO2_y', 'RSPM_PM10_y', 'SO2_y', 'SPM_y', 'month_number_diff_y',
       'P10_NO2_MOM_diff', 'P10_SO2_MOM_diff', 'P10_RSPM_PM10_MOM_diff',
       'P10_SPM_MOM_diff', 'ID', 'month_number', 'year_number', 'NO2',
       'RSPM_PM10', 'SO2', 'SPM', 'month_number_diff', 'P90_NO2_MOM_diff',
       'P90_SO2_MOM_diff', 'P90_RSPM_PM10_MOM_diff', 'P90_SPM_MOM_diff'],
      dtype='object')

In [27]:
df_final=df_final[[ 'City_Town_Village_Area', 'Type_of_Location', 'TS',
       'year_number_x', 'month_number_x', 'NO2_x', 'RSPM_PM10_x', 'SO2_x',
       'SPM_x', 'Median_SO2_MOM_diff', 'Median_NO2_MOM_diff', 'Median_RSPM_PM10_MOM_diff',
       'Median_SPM_MOM_diff', 'NO2_y', 'RSPM_PM10_y', 'SO2_y', 'SPM_y', 
       'P10_NO2_MOM_diff', 'P10_SO2_MOM_diff', 'P10_RSPM_PM10_MOM_diff',
       'P10_SPM_MOM_diff', 'NO2','RSPM_PM10', 'SO2', 'SPM', 'month_number_diff', 'P90_NO2_MOM_diff',
       'P90_SO2_MOM_diff', 'P90_RSPM_PM10_MOM_diff', 'P90_SPM_MOM_diff']]

In [31]:
df_final[['NO2_y','NO2_x','NO2']].head()

   NO2_y  NO2_x   NO2
0   10.4   12.0  14.4
1   10.2   11.0  11.8
2   10.0   10.0  10.0
3   12.6   14.0  15.0
4   11.0   14.0  14.6

In [32]:
df_final.columns

Index(['City_Town_Village_Area', 'Type_of_Location', 'TS', 'year_number_x',
       'month_number_x', 'NO2_x', 'RSPM_PM10_x', 'SO2_x', 'SPM_x',
       'Median_SO2_MOM_diff', 'Median_NO2_MOM_diff',
       'Median_RSPM_PM10_MOM_diff', 'Median_SPM_MOM_diff', 'NO2_y',
       'RSPM_PM10_y', 'SO2_y', 'SPM_y', 'P10_NO2_MOM_diff', 'P10_SO2_MOM_diff',
       'P10_RSPM_PM10_MOM_diff', 'P10_SPM_MOM_diff', 'NO2', 'RSPM_PM10', 'SO2',
       'SPM', 'month_number_diff', 'P90_NO2_MOM_diff', 'P90_SO2_MOM_diff',
       'P90_RSPM_PM10_MOM_diff', 'P90_SPM_MOM_diff'],
      dtype='object')

In [33]:
df_final.columns=['City_Town_Village_Area', 'Type_of_Location', 'TS', 'year_number',
       'month_number', 'NO2_Median', 'RSPM_PM10_Median', 'SO2_Median', 'SPM_Median',
       'Median_SO2_MOM_diff', 'Median_NO2_MOM_diff',
       'Median_RSPM_PM10_MOM_diff', 'Median_SPM_MOM_diff', 'NO2_P10',
       'RSPM_PM10_P10', 'SO2_P10', 'SPM_P10', 'P10_NO2_MOM_diff', 'P10_SO2_MOM_diff',
       'P10_RSPM_PM10_MOM_diff', 'P10_SPM_MOM_diff', 'NO2_P90', 'RSPM_PM10_P90', 'SO2_P90',
       'SPM_P90', 'month_number_diff', 'P90_NO2_MOM_diff', 'P90_SO2_MOM_diff',
       'P90_RSPM_PM10_MOM_diff', 'P90_SPM_MOM_diff']

In [ ]:
df_final.to_csv(path_or_buf ='D:\personal\MS\EDA\MOM_P105090.csv')

In [40]:
df_final_bkp=df_final

In [43]:
df_final.sort_values(['City_Town_Village_Area', 'Type_of_Location','month_number','year_number'],inplace=True,ascending=True)

In [45]:
df_final.head(n=100)

,City_Town_Village_Area,Type_of_Location,TS,year_number,month_number,NO2_Median,RSPM_PM10_Median,SO2_Median,SPM_Median,Median_SO2_MOM_diff,...,P10_SPM_MOM_diff,NO2_P90,RSPM_PM10_P90,SO2_P90,SPM_P90,month_number_diff,P90_NO2_MOM_diff,P90_SO2_MOM_diff,P90_RSPM_PM10_MOM_diff,P90_SPM_MOM_diff
0,Akola,Industrial,20110010,2011,1,12.0,149.000000,11.00,NaN,NaN,...,NaN,14.40,153.800000,12.60,NaN,NaN,NaN,NaN,NaN,NaN
12,Akola,Industrial,20120010,2012,1,11.0,137.000000,9.50,NaN,-2.00,...,NaN,12.00,147.730000,11.00,NaN,-11.0,-1.90,-1.30,-12.170000,NaN
24,Akola,Industrial,20130010,2013,1,11.5,155.000000,10.00,NaN,-1.50,...,NaN,13.00,161.200000,11.00,NaN,-11.0,-1.00,-1.00,5.397000,NaN
31,Akola,Industrial,20150010,2015,1,9.0,127.000000,7.00,NaN,-1.00,...,NaN,10.00,128.200000,8.00,NaN,-11.0,0.00,0.00,-13.800000,NaN
1,Akola,Industrial,20110020,2011,2,11.0,143.000000,9.00,NaN,-2.00,...,NaN,11.80,147.800000,9.80,NaN,1.0,-2.60,-2.80,-6.000000,NaN
13,Akola,Industrial,20120020,2012,2,13.0,150.335000,11.00,NaN,1.50,...,NaN,14.00,157.232000,12.00,NaN,1.0,2.00,1.00,9.502000,NaN
25,Akola,Industrial,20130020,2013,2,12.0,146.500000,10.00,NaN,0.00,...,NaN,12.00,150.300000,10.00,NaN,1.0,-1.00,-1.00,-10.900000,NaN
32,Akola,Industrial,20150020,2015,2,9.5,129.000000,8.00,NaN,1.00,...,NaN,10.00,130.000000,8.00,NaN,1.0,0.00,0.00,1.800000,NaN
2,Akola,Industrial,20110030,2011,3,10.0,139.000000,9.00,NaN,0.00,...,NaN,10.00,139.000000,9.00,NaN,1.0,-1.80,-0.80,-8.800000,NaN
14,Akola,Industrial,20120030,2012,3,13.0,161.670000,12.00,NaN,1.00,...,NaN,14.00,164.070000,12.00,NaN,1.0,0.00,0.00,6.838000,NaN
33,Akola,Industrial,20150030,2015,3,9.5,127.000000,8.00,NaN,0.00,...,NaN,10.30,131.300000,8.30,NaN,1.0,0.30,0.30,1.300000,NaN
3,Akola,Industrial,20110040,2011,4,14.0,165.000000,12.00,NaN,3.00,...,NaN,15.00,166.000000,13.00,NaN,1.0,5.00,4.00,27.000000,NaN
15,Akola,Industrial,20120040,2012,4,11.5,150.670000,10.50,NaN,-1.50,...,NaN,13.60,162.500000,12.30,NaN,1.0,-0.40,0.30,-1.570000,NaN
34,Akola,Industrial,20150040,2015,4,9.0,125.000000,7.00,NaN,-1.00,...,NaN,10.00,127.100000,7.10,NaN,1.0,-0.30,-1.20,-4.200000,NaN
4,Akola,Industrial,20110050,2011,5,14.0,148.000000,12.00,NaN,0.00,...,NaN,14.60,161.200000,13.00,NaN,1.0,-0.40,0.00,-4.800000,NaN
16,Akola,Industrial,20120050,2012,5,14.5,159.000000,13.00,NaN,2.50,...,NaN,15.10,166.330000,13.00,NaN,1.0,1.50,0.70,3.830000,NaN
35,Akola,Industrial,20150050,2015,5,9.5,126.500000,8.00,NaN,1.00,...,NaN,10.00,130.300000,8.00,NaN,1.0,0.00,0.90,3.200000,NaN
5,Akola,Industrial,20110060,2011,6,11.0,126.000000,9.00,NaN,-3.00,...,NaN,12.80,146.400000,10.80,NaN,1.0,-1.80,-2.20,-14.800000,NaN
17,Akola,Industrial,20120060,2012,6,12.0,139.330000,11.00,NaN,-2.00,...,NaN,14.00,151.602000,13.00,NaN,1.0,-1.10,0.00,-14.728000,NaN
36,Akola,Industrial,20150060,2015,6,9.0,121.500000,7.00,NaN,-1.00,...,NaN,10.00,124.000000,8.00,NaN,1.0,0.00,0.00,-6.300000,NaN
6,Akola,Industrial,20110070,2011,7,10.0,113.000000,7.00,NaN,-2.00,...,NaN,11.60,134.600000,8.90,NaN,1.0,-1.20,-1.90,-11.800000,NaN
18,Akola,Industrial,20120070,2012,7,11.0,125.000000,9.00,NaN,-2.00,...,NaN,12.00,146.870000,10.40,NaN,1.0,-2.00,-2.60,-4.732000,NaN
37,Akola,Industrial,20150070,2015,7,9.0,124.000000,7.00,NaN,0.00,...,NaN,10.00,126.100000,8.10,NaN,1.0,0.00,0.10,2.100000,NaN
7,Akola,Industrial,20110080,2011,8,9.0,131.000000,8.00,NaN,1.00,...,NaN,13.00,151.800000,11.00,NaN,1.0,1.40,2.10,17.200000,NaN
19,Akola,Industrial,20120080,2012,8,11.5,120.500000,9.00,NaN,0.00,...,NaN,12.30,143.099000,10.00,NaN,1.0,0.30,-0.40,-3.771000,NaN
26,Akola,Industrial,20130080,2013,8,8.0,121.000000,7.00,NaN,NaN,...,NaN,9.00,125.400000,7.40,NaN,6.0,NaN,NaN,NaN,NaN
8,Akola,Industrial,20110090,2011,9,10.0,136.000000,8.00,NaN,0.00,...,NaN,10.90,145.900000,9.90,NaN,1.0,-2.10,-1.10,-5.900000,NaN
20,Akola,Industrial,20120090,2012,9,10.0,127.665000,9.00,NaN,0.00,...,NaN,12.00,146.530000,10.30,NaN,1.0,-0.30,0.30,3.431000,NaN
27,Akola,Industrial,20130090,2013,9,8.0,122.000000,7.00,NaN,0.00,...,NaN,8.30,126.000000,7.00,NaN,1.0,-0.70,-0.40,0.600000,NaN
38,Akola,Industrial,20150090,2015,9,10.0,129.000000,9.00,NaN,NaN,...,NaN,10.20,133.400000,9.20,NaN,2.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,Akola,Residential,20140070,2014,7,9.5,162.000000,9.00,NaN,-1.00,...,NaN,10.70,167.400000,9.00,NaN,1.0,0.70,-1.00,1.400000,NaN
91,Akola,Residential,20150070,2015,7,7.0,135.000000,7.00,NaN,1.00,...,NaN,9.00,140.800000,8.00,NaN,1.0,0.40,0.40,0.200000,NaN
49,Akola,Residential,20110080,2011,8,8.0,118.000000,6.00,NaN,0.50,...,NaN,8.70,126.800000,7.00,NaN,1.0,-3.30,0.00,0.800000,NaN
61,Akola,Residential,20120080,2012,8,10.0,115.000000,7.00,NaN,0.00,...,NaN,11.00,150.266000,8.00,NaN,1.0,0.00,-1.20,-11.334000,NaN
68,Akola,Residential,20130080,2013,8,8.0,125.666667,7.00,NaN,NaN,...,NaN,9.00,132.700000,8.00,NaN,6.0,NaN,NaN,NaN,NaN
80,Akola,Residential,20140080,2014,8,9.0,126.500000,8.00,NaN,-1.00,...,NaN,10.00,165.500000,9.00,NaN,1.0,-0.70,0.00,-1.900000,NaN
50,Akola,Residential,20110090,2011,9,10.0,121.000000,6.00,NaN,0.00,...,NaN,11.00,131.900000,8.40,NaN,1.0,2.30,1.40,5.100000,NaN
62,Akola,Residential,20120090,2012,9,9.0,131.000000,8.00,NaN,1.00,...,NaN,10.40,159.268000,9.00,NaN,1.0,-0.60,1.00,9.002000,NaN
69,Akola,Residential,20130090,2013,9,8.0,119.000000,6.00,NaN,-1.00,...,NaN,8.00,138.266667,7.00,NaN,1.0,-1.00,-1.00,5.566667,NaN
81,Akola,Residential,20140090,2014,9,8.0,119.000000,6.50,NaN,-1.50,...,NaN,8.50,128.000000,7.50,NaN,1.0,-1.50,-1.50,-37.500000,NaN
92,Akola,Residential,20150090,2015,9,7.0,113.000000,6.00,NaN,NaN,...,NaN,7.00,140.000000,7.00,NaN,2.0,NaN,NaN,NaN,NaN
51,Akola,Residential,20110100,2011,10,8.0,128.000000,7.00,NaN,1.00,...,NaN,10.00,135.000000,9.00,NaN,1.0,-1.00,0.60,3.100000,NaN
63,Akola,Residential,20120100,2012,10,9.0,131.000000,8.00,NaN,0.00,...,NaN,12.00,156.798000,9.20,NaN,1.0,1.60,0.20,-2.470000,NaN
70,Akola,Residential,20130100,2013,10,7.0,115.000000,6.00,NaN,0.00,...,NaN,8.00,139.133333,7.40,NaN,1.0,0.00,0.40,0.866667,NaN
82,Akola,Residential,20140100,2014,10,8.0,146.500000,7.00,NaN,0.50,...,NaN,10.20,162.500000,8.60,NaN,1.0,1.70,1.10,34.500000,NaN
93,Akola,Residential,20150100,2015,10,8.0,135.500000,7.00,NaN,1.00,...,NaN,9.00,143.600000,8.00,NaN,1.0,2.00,1.00,3.600000,NaN
52,Akola,Residential,20110110,2011,11,9.0,130.000000,7.00,NaN,0.00,...,NaN,9.30,132.600000,8.00,NaN,1.0,-0.70,-1.00,-2.400000,NaN
64,Akola,Residential,20120110,2012,11,10.0,141.000000,8.00,NaN,0.00,...,NaN,12.20,164.802000,10.40,NaN,1.0,0.20,1.20,8.004000,NaN
71,Akola,Residential,20130110,2013,11,7.0,142.333333,6.00,NaN,0.00,...,NaN,8.00,144.000000,6.30,NaN,1.0,0.00,-1.10,4.866667,NaN
83,Akola,Residential,20140110,2014,11,9.0,147.000000,7.00,NaN,0.00,...,NaN,11.20,171.000000,10.00,NaN,1.0,1.00,1.40,8.500000,NaN
94,Akola,Residential,20150110,2015,11,8.5,141.000000,7.00,NaN,0.00,...,NaN,10.50,166.000000,9.50,NaN,1.0,1.50,1.50,22.400000,NaN
53,Akola,Residential,20110120,2011,12,9.0,134.000000,8.00,NaN,1.00,...,NaN,10.30,137.300000,8.00,NaN,1.0,1.00,0.00,4.700000,NaN
65,Akola,Residential,20120120,2012,12,10.0,143.670000,9.00,NaN,1.00,...,NaN,12.00,172.070000,11.00,NaN,1.0,-0.20,0.60,7.268000,NaN
72,Akola,Residential,20130120,2013,12,8.0,128.000000,7.00,NaN,1.00,...,NaN,8.00,152.433333,7.30,NaN,1.0,0.00,1.00,8.433333,NaN
84,Akola,Residential,20140120,2014,12,9.0,142.000000,8.00,NaN,1.00,...,NaN,10.30,154.700000,8.60,NaN,1.0,-0.90,-1.40,-16.300000,NaN
95,Akola,Residential,20150120,2015,12,8.0,115.000000,7.00,NaN,0.00,...,NaN,9.00,145.400000,8.40,NaN,1.0,-1.50,-1.10,-20.600000,NaN
96,Amravati,Industrial,20060010,2006,1,12.4,NaN,11.30,NaN,NaN,...,NaN,12.40,NaN,11.30,NaN,NaN,NaN,NaN,NaN,NaN
101,Amravati,Industrial,20070010,2007,1,13.1,69.000000,10.05,NaN,-1.35,...,NaN,15.00,69.800000,12.80,NaN,-11.0,-1.40,-0.05,NaN,NaN
113,Amravati,Industrial,20080010,2008,1,12.0,45.000000,8.30,NaN,-0.70,...,NaN,12.98,73.200000,10.48,NaN,-11.0,-3.10,-1.14,2.900000,NaN
125,Amravati,Industrial,20090010,2009,1,12.5,80.000000,10.80,NaN,0.30,...,NaN,13.84,87.800000,11.60,NaN,-11.0,1.22,0.70,8.000000,NaN

In [47]:
df_final.set_index(['City_Town_Village_Area', 'Type_of_Location'],inplace=True)

In [48]:
##time
df_final['year_number_diff']=df_final.year_number-df_final.groupby(level=['City_Town_Village_Area', 'Type_of_Location'])['year_number'].shift(1)

#################################
#Median
##NO2
df_final['NO2_Median_YOY_diff']=df_final['NO2_Median']-df_final.groupby(level=['City_Town_Village_Area', 'Type_of_Location'])['NO2_Median'].shift(1)
df_final.loc[~(df_final.year_number_diff==1) ,'NO2_Median_YOY_diff']=None
##SO2
df_final['SO2_Median_YOY_diff']=df_final['SO2_Median']-df_final.groupby(level=['City_Town_Village_Area', 'Type_of_Location'])['SO2_Median'].shift(1)
df_final.loc[~(df_final.year_number_diff==1) ,'SO2_Median_YOY_diff']=None
##RSPM_PM10
df_final['RSPM_PM10_Median_YOY_diff']=df_final['RSPM_PM10_Median']-df_final.groupby(level=['City_Town_Village_Area', 'Type_of_Location'])['RSPM_PM10_Median'].shift(1)
df_final.loc[~(df_final.year_number_diff==1) ,'RSPM_PM10_Median_YOY_diff']=None

##SPM
df_final['SPM_Median_YOY_diff']=df_final['SPM_Median']-df_final.groupby(level=['City_Town_Village_Area', 'Type_of_Location'])['SPM_Median'].shift(1)
df_final.loc[~(df_final.year_number_diff==1) ,'SPM_Median_YOY_diff']=None
#################################################
##P10
##NO2
df_final['NO2_P10_YOY_diff']=df_final['NO2_P10']-df_final.groupby(level=['City_Town_Village_Area', 'Type_of_Location'])['NO2_P10'].shift(1)
df_final.loc[~(df_final.year_number_diff==1) ,'NO2_P10_YOY_diff']=None
##SO2
df_final['SO2_P10_YOY_diff']=df_final['SO2_P10']-df_final.groupby(level=['City_Town_Village_Area', 'Type_of_Location'])['SO2_P10'].shift(1)
df_final.loc[~(df_final.year_number_diff==1) ,'SO2_P10_YOY_diff']=None
##RSPM_PM10
df_final['RSPM_PM10_P10_YOY_diff']=df_final['RSPM_PM10_P10']-df_final.groupby(level=['City_Town_Village_Area', 'Type_of_Location'])['RSPM_PM10_P10'].shift(1)
df_final.loc[~(df_final.year_number_diff==1) ,'RSPM_PM10_P10_YOY_diff']=None

##SPM
df_final['SPM_P10_YOY_diff']=df_final['SPM_P10']-df_final.groupby(level=['City_Town_Village_Area', 'Type_of_Location'])['SPM_P10'].shift(1)
df_final.loc[~(df_final.year_number_diff==1) ,'SPM_P10_YOY_diff']=None

#########################################################
##P90
##NO2
df_final['NO2_P90_YOY_diff']=df_final['NO2_P90']-df_final.groupby(level=['City_Town_Village_Area', 'Type_of_Location'])['NO2_P90'].shift(1)
df_final.loc[~(df_final.year_number_diff==1) ,'NO2_P90_YOY_diff']=None
##SO2
df_final['SO2_P90_YOY_diff']=df_final['SO2_P90']-df_final.groupby(level=['City_Town_Village_Area', 'Type_of_Location'])['SO2_P90'].shift(1)
df_final.loc[~(df_final.year_number_diff==1) ,'SO2_P90_YOY_diff']=None
##RSPM_PM10
df_final['RSPM_PM10_P90_YOY_diff']=df_final['RSPM_PM10_P90']-df_final.groupby(level=['City_Town_Village_Area', 'Type_of_Location'])['RSPM_PM10_P90'].shift(1)
df_final.loc[~(df_final.year_number_diff==1) ,'RSPM_PM10_P90_YOY_diff']=None

##SPM
df_final['SPM_P90_YOY_diff']=df_final['SPM_P90']-df_final.groupby(level=['City_Town_Village_Area', 'Type_of_Location'])['SPM_P90'].shift(1)
df_final.loc[~(df_final.year_number_diff==1) ,'SPM_P90_YOY_diff']=None

In [50]:
df_final.reset_index(inplace=True)

In [51]:
df_final.to_csv(path_or_buf ='D:\personal\MS\EDA\YOY_P105090_all.csv')